// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm74uTPYCB46o5V5qsSLleRzMdV6qbM9I',
    appId: '1:772144222105:web:bcb3e430f440bb415d0d08',
    messagingSenderId: '772144222105',
    projectId: 'all-demo-projects-31469',
    authDomain: 'all-demo-projects-31469.firebaseapp.com',
    databaseURL: 'https://all-demo-projects-31469-default-rtdb.firebaseio.com',
    storageBucket: 'all-demo-projects-31469.appspot.com',
    measurementId: 'G-FT8GNQ4XJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWW0kKW1QKj748yYPUoYoU5bxbXNK4uCg',
    appId: '1:772144222105:android:5fdd5ffabb0c47c85d0d08',
    messagingSenderId: '772144222105',
    projectId: 'all-demo-projects-31469',
    databaseURL: 'https://all-demo-projects-31469-default-rtdb.firebaseio.com',
    storageBucket: 'all-demo-projects-31469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOjB_JQ8DTF9rxcYdWq-vbzWMNyoq1uxc',
    appId: '1:772144222105:ios:8c61646f21723dc65d0d08',
    messagingSenderId: '772144222105',
    projectId: 'all-demo-projects-31469',
    databaseURL: 'https://all-demo-projects-31469-default-rtdb.firebaseio.com',
    storageBucket: 'all-demo-projects-31469.appspot.com',
    androidClientId: '772144222105-10e5ilttl2423ndl2ioqqckvfko0fbcl.apps.googleusercontent.com',
    iosClientId: '772144222105-15l8qvjqabdkieluupgq4m43e2qv0vk9.apps.googleusercontent.com',
    iosBundleId: 'com.shahi.firebasePushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOjB_JQ8DTF9rxcYdWq-vbzWMNyoq1uxc',
    appId: '1:772144222105:ios:67d8cf717975527b5d0d08',
    messagingSenderId: '772144222105',
    projectId: 'all-demo-projects-31469',
    databaseURL: 'https://all-demo-projects-31469-default-rtdb.firebaseio.com',
    storageBucket: 'all-demo-projects-31469.appspot.com',
    androidClientId: '772144222105-10e5ilttl2423ndl2ioqqckvfko0fbcl.apps.googleusercontent.com',
    iosClientId: '772144222105-taie2056tlmrmguu1h76cu69rcp5atm7.apps.googleusercontent.com',
    iosBundleId: 'com.shahi.firebasePushNotificationApp.RunnerTests',
  );
}
